Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FormatString:
  Enabled: false

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'mqtt.gemspec'
    - 'examples/**'
    - 'spec/**/*'
